# Generated by Django 4.2.29 on 2026-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('maiz', 'Maíz'), ('platano', 'Plátano'), ('arroz', 'Arroz'), ('cafe', 'Café'), ('yuca', 'Yuca')], max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('ciclo_dias', models.IntegerField(help_text='Días promedio desde siembra a cosecha')),
                ('rendimiento_min_m2', models.FloatField(help_text='Kg mínimos por metro cuadrado')),
                ('rendimiento_max_m2', models.FloatField(help_text='Kg máximos por metro cuadrado')),
            ],
        ),
    ]
