# Generated by Django 4.2.29 on 2026-03-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra', models.DateField()),
                ('area_m2', models.FloatField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='PasoCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('instrucciones', models.TextField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='cultivos.cultivo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
