# Generated by Django 4.2.29 on 2026-03-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0002_planificacion_pasocultivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacion',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='planificacion',
            name='estado',
            field=models.CharField(choices=[('amazonas', 'Amazonas'), ('anzoategui', 'Anzoátegui'), ('apure', 'Apure'), ('aragua', 'Aragua'), ('barinas', 'Barinas'), ('bolivar', 'Bolívar'), ('carabobo', 'Carabobo'), ('cojedes', 'Cojedes'), ('delta_amacuro', 'Delta Amacuro'), ('distrito_capital', 'Distrito Capital'), ('falcon', 'Falcón'), ('guarico', 'Guárico'), ('lara', 'Lara'), ('merida', 'Mérida'), ('miranda', 'Miranda'), ('monagas', 'Monagas'), ('nueva_esparta', 'Nueva Esparta'), ('portuguesa', 'Portuguesa'), ('sucre', 'Sucre'), ('tachira', 'Táchira'), ('trujillo', 'Trujillo'), ('vargas', 'La Guaira'), ('yaracuy', 'Yaracuy'), ('zulia', 'Zulia')], default='barinas', max_length=50),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='suelo',
            field=models.CharField(choices=[('optimo', 'Suelo Suelto / Muy Fértil'), ('medio', 'Suelo Normal'), ('dificil', 'Suelo Duro / Arcilloso')], default='medio', max_length=20),
        ),
    ]
